# Generated by Django 4.2.6 on 2023-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_tag_order_book_order_costumer_alter_order_stauts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tages',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stauts',
            field=models.CharField(choices=[('Sool', 'Sool'), ('Peding', 'Peding'), ('Delivred', 'Delivred')], max_length=190, null=True),
        ),
    ]
