# Generated by Django 4.2.6 on 2023-10-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_order_stauts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stauts',
            field=models.CharField(choices=[('Peding', 'Peding'), ('in progress', 'in progress'), ('Delivred', 'Delivred'), ('out of order', 'out of order')], max_length=190, null=True),
        ),
    ]
