# Generated by Django 4.2.6 on 2023-11-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_order_stauts'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='stauts',
            field=models.CharField(choices=[('Peding', 'Peding'), ('Delivred', 'Delivred'), ('out of order', 'out of order'), ('in progress', 'in progress')], max_length=190, null=True),
        ),
    ]
