# Generated by Django 4.2.7 on 2023-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_order_stauts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stauts',
            field=models.CharField(choices=[('in progress', 'in progress'), ('Delivred', 'Delivred'), ('out of order', 'out of order'), ('Peding', 'Peding')], max_length=190, null=True),
        ),
    ]
